### ISSUE TITLE
Missing package 'serial'

### ISSUE THREAD

**Issue by PaddyCube** [NRottmann/AutonomousLawnMowerROS#1]
Hello,

I wanted to try this robot in simulation. After clone, catkin_make fails because it is unable to find package 'serial'.

```
Make Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "serial" with any
  of the following names:

    serialConfig.cmake
    serial-config.cmake
```
It seems to me that this is not related to rosserial. Could you please share which serial package you use here? Is it this one? http://wiki.ros.org/serial

As I'm on ROS Noetic, there is no package named ros-noetic-serial

Thanks
Patrick

**Comment by PaddyCube** [comment]
Yes, it is the package I mentioned myself. Just for reference for others, instructions can be found here http://wjwwood.io/serial/ and it works for ROS Noetic as well.

Thanks for sharing this project. It is the first time I see someone uses ROS for lawn mowers together with inexpensive perimeter wire.

**Comment by tkazik** [comment]
linking here for tracking: https://github.com/wjwwood/serial/issues/222
